### ISSUE TITLE
Backend API RBAC management

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#109]
The Sensu Backend API needs to support RBAC management. This includes the RBAC Roles, Organizations, Environments, and Groups, as proposed - https://github.com/sensu/engineering/wiki/RBAC#proposal.

A very basic permission model visual can be found at https://github.com/sensu/engineering/wiki/RBAC#examples-1

How Group Object Type and Object Instance permissions are configured is TBD. We are operating on the assumption that this will "shake out" as we implement RBAC and apply it throughout Sensu.

## TODO

- [ ] Determine how to store RBAC data in etcd
- [ ] Create Backend Store (etcd) "views" for RBAC
- [ ] Define and create RBAC Backend API endpoints
- [ ] Apply RBAC to the Backend API
