### ISSUE TITLE
Add "Organization" & "Environment" to Sensu Object Types

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#110]
Sensu RBAC requires all Object Types (Entity, Check, etc.) to have an Organization and Environment. The RBAC proposed spec provides some explanation - https://github.com/sensu/engineering/wiki/RBAC#proposal

Object Types need Organization and Environment defaults. Taken from the proposed spec:

By default, every Sensu User, Entity, and Object (i.e. check) is a member of the Organization "default".

By default, every Entity, and Object (i.e. check) is a member of the Environment "default".

## TODO

- [ ] Add "Organization" to each Sensu Object Type with a JSON tag "organization"
- [ ] Add "Environment" to each Sensu Object Type with a JSON tag "environment"
- [ ] Update Agent Entity creation to include Organization and Environment defaults
- [ ] Update Agent Entity creation to include configurable Organization and Environment
- [ ] Update Backend API endpoints to include Organization and Environment defaults
