### ISSUE TITLE
[Web UI] Global Error handling

### ISSUE THREAD

**Issue by 10xjs** [sensu/sensu-go#1299]
## What
Set up a global error detection system connected where _any_ unhandled exception or promise rejection will trigger a global error state.

## Why
There is no immediate consequence to not-catching an exception, the environment will attempt to continue in a potentially compromised state.

This will force the code we write to be far more stable and will prevent bugs from surviving beyond the dev phase.

## How
Using [`bugnet`](https://www.npmjs.com/package/bugnet), we can tap into global `unhandledrejection` and `onerror` events and connect this to trigger a blocking error state (probably a modal overlay). This will require that any new functionality that has the potential to throw exceptions will make a lot of noise if we forget to include necessary local error handling.

## Concerns
We would be _intentionally_ introducing a app-crash state, even in production builds. We would need to be more strict and include error handling code for even the rarest edge-cases where we expect errors to be thrown. We could no longer rely on JavaScript's error-ignoring fault-tolerance "feature". 

Some libs will internally silence errors. (`apollo-client` wraps the mutation `update` function in a silencing `try` `catch` that prevents _any_ errors from ever being caught downstream. Our supplied `update` function must have internal error handling.) There are other places where errors are internally caught and provided as function arguments (`react-apollo/Query` component render handler, for example) requiring us to manually check for and potentially re-throw the error.

If any additional script files are added to the page, our error detection system will need to be configured to detect the source file of any caught error and to ignore errors from "vendor" code. (This can be achieved by comparing that the source path in an error's top stack frame to the `__webpack_public_path__` global var.)

## Questions
- Would a dismissable alert instead of  blocking error state that _requires_ an app refresh be a better choice?

## Tasks
- [x] Set up `bugnet` (Parent of #1356)
- [x] Polyfill `Promise` with `bluebird`(Parent of  #1357)
- [x] Ignore non-bundle errors (Parent of #1358)
- [x] Global error dialog (Parent of #1360)

**Comment by portertech** [comment]
As we discussed, we believe this is the right thing to do.
