### ISSUE TITLE
 [Web UI] Events Page

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/sensu-go#1579]
Where valuable bring v2 up to feature parity with Uchiwa.

## 📝 TODO

- [x] state of list elements should be realtime (Parent of #1578)
- [ ] filter by silenced state (Parent of #1576)
- [x] filter by state of occurrence threshold (Parent of #1577)
- [x] hook up silenced form (Parent of #1569)
- [x] add pagination (Parent of #1369)
- [x] event details (Parent of #1570)
