### ISSUE TITLE
[Web UI] Entities Page

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/sensu-go#1584]
Where valuable bring v2 up to feature parity with Uchiwa.

## 📝 TODO

- [x] realtime (parent of #1583)
- [x] filter by subscription (parent of #1582)
- [x] bulk delete (parent of #1581)
- [ ] bulk un-silence (parent of #1580)
- [x] create silences (parent of #1569) 
- [x] pagination (parent of #1369) 
- [x] sorting (parent of #1571)
