### ISSUE TITLE
[Web UI] Checks Page

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/sensu-go#1684]
Where valuable bring v2 up to feature parity with Uchiwa.

## 📝 TODO

- [x] list (parent of #1685)
- [x] filtering (parent of #1678)
- [ ] bulk issue check requests (parent of #1679)
- [ ] bulk silence (parent of #1682)
- [ ] bulk un-silence (parent of #1680)
- [x] sort by name (parent of #1683)
- [x] realtime (parent of #1681)
- [ ] details (parent of #847 )
