### ISSUE TITLE
Add an endpoint in the backend API to expose Sensu version

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-go#1739]
### Todo

- [ ] Determine the name of the endpoint (`/info`? `/version`?)
- [ ] Expose sensu-backend version
- [ ] Expose etcd cluster version
  - The etcd [client](https://godoc.org/github.com/etcd-io/etcd/client) (not the v3 client), exposes a `GetVersion` call.

**Comment by amdprophet** [comment]
Here's an example response from the `/info` endpoint in 1.x:

```
{"sensu":{"version":"1.4.2","enterprise_version":"2.8.3","settings":{"hexdigest":"c88da3ee0b6e0a81c96c35158adbb229aa16d6c98b5348a7f121eaf15e1d2de6"}},"transport":{"name":"rabbitmq","keepalives":{"messages":0,"consumers":1},"results":{"messages":0,"consumers":1},"connected":true},"redis":{"connected":true},"servers":[{"id":"9285bf49-19b9-4313-9d92-1e3ad7547cd3","hostname":"localhost","address":"10.0.0.50","tasks":["check_request_publisher","metric_calculator","client_monitor","check_result_monitor","metric_counter_pruner"],"metrics":{"cpu":{"user":22432.21875,"system":1582.4453125}},"sensu":{"version":"1.4.2","enterprise_version":"2.8.3","settings":{"hexdigest":"c88da3ee0b6e0a81c96c35158adbb229aa16d6c98b5348a7f121eaf15e1d2de6"}},"tessen":{"enabled":false},"timestamp":1537205291}]}
```

**Comment by cyphus** [comment]
The 1.x `/info` endpoint contains some health and metrics info as well. Since we already have `/health` in 2.x, how about we specifically add a `/version` endpoint to return just version info? Nicer separation of concerns that way.
