### ISSUE TITLE
[Web UI] Check Details View

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/sensu-go#1774]
As a user I should be able to click a check and have all it’s configuration details presented.

## 📝 TODO

- [ ] Discussion: do we break away from Uchiwa and make this a modal? At least in the near term the details displayed are very limited.
- [ ] Silence
- [ ] Issue adhoc check request
- [ ] Display configuration details of the check
