### ISSUE TITLE
[Web UI] Silences Page

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/sensu-go#1776]
As a user I should be able to view all currently valid silenced entries.

## 📝 TODO

- [x] User should be able to create a new silence
- [ ] User should have the option to have the page automatically reflect changes. (Polling.)
- [x] User should be able to filter the list of entries. (w/ SQE.)
- [x] List of items should be paginated.
- [x] User should be able to delete one or more silences. (Bulk delete.)
- [x] User should be presented with a list that displays the most import details of each silence.
