### ISSUE TITLE
[Web UI] Silence Details View

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/sensu-go#1777]
As a user I should be able to click a silenced entry and have all it’s configuration details presented.

## 📝 TODO

- [ ] Discussion: do we break away from Uchiwa and make this a modal? At least in the near term the details displayed are very limited.
- [ ] Details should automatically reflect any remote changes. (Polling.)
- [ ] User should be able to delete the silence.
- [ ] User should be presented with all configuration details.

**Comment by jamesdphillips** [comment]
All relevant fields are represented in the list view. Removing from milestone.
