### ISSUE TITLE
Add organizations to sensu-cli

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#205]
- [x] A CLI profile includes an organization
- [ ] ~When interacting with objects, the profile's organization is used by default~ (Moved to https://github.com/sensu/sensu-go/issues/237)
- [ ] ~When interacting with objects, I can override the profile's default organization using an additional flag (e.g. `--organization`)~ (Moved to https://github.com/sensu/sensu-go/issues/224)
- [ ]  ~When interacting with objects, I can query across all organizations (that I have access to) using an additional flag (e.g. `--all-organizations`)~ (Moved to https://github.com/sensu/sensu-go/issues/224)
