### ISSUE TITLE
Expose Sensu version information

### ISSUE THREAD

**Issue by palourde** [sensu/sensu-go#2083]
As an `operator`
I want `detailed version information about Sensu`
so that `I can better troubleshooting problems.`

### Acceptance Criteria

* The version information can be remotely retrieved, without having local access to running process.
  * sensu-backend API
  * sensuctl
* Detailed information about Sensu and its components are provided:
  * sensu-backend version
  * sensu-backend build number (git SHA or other)
  * sensu-backend build date
  * etcd cluster version, whether it's embedded or remote
* This information should still be accessible even if a component (e.g. etcd) is unavailable, except the particular information for the given component
  * In this particular case, the information should be blank for that component
* The preferred encoding format for this information should JSON
  * Bonus: look for Content-Type header in the HTTP request 
* The endpoint should be secured behind authentication
  * We need to determine the level of access required (admin? all users?)

### Tasks

- [ ] Parent of https://github.com/sensu/sensu-go/issues/1739
- [ ] Parent of https://github.com/sensu/sensu-go/issues/2040
- [ ] Parent of https://github.com/sensu/sensu-go/issues/2085

### Demo

* I can see all Sensu version information via sensuctl
* I can see this information via the API endpoint
* I can't see the information via when unauthenticated
* When a component is unavailable, the information for this component will be missing

**Comment by palourde** [comment]
Duplicated of https://github.com/sensu/sensu-go/issues/2040
