### ISSUE TITLE
Spike on teasing apart authorization and apid. 

### ISSUE THREAD

**Issue by annaplotkin** [sensu/sensu-go#2145]
Tease apart authorization and apiD to use the new model and auth workflow.

Requires #2107

**Comment by palourde** [comment]
## Todo

- [ ] Create a WithRequestInfo (name TBD) middleware (see https://github.com/kubernetes/apiserver/blob/e9e4beec4b157a40f6c742782d74faf45c2b280e/pkg/endpoints/request/requestinfo.go#L116)
	- [ ] We should store the something like this in the request context: https://github.com/grepory/storage/blob/3886dbfcfedb33caf8af447c78fec71c586a35d1/authorization/interface.go#L13 (minus the User, which should be done by the authentication middleware)
- [ ] Add a group field for users
	- [ ] Add support in sensuctl
- [ ] Store the user's group into the JWT. See https://github.com/sensu/sensu-go/blob/f5b8db4d5d75c9ed9960ff6d5ed5bd905a3f9812/types/token.go#L7 https://github.com/sensu/sensu-go/blob/f5b8db4d5d75c9ed9960ff6d5ed5bd905a3f9812/backend/apid/middlewares/authentication.go#L35
- [ ] Create RBAC types (see https://github.com/grepory/storage/tree/master/apis/rbac)
- [ ] Create new RBAC pkg (see https://github.com/grepory/storage/tree/master/authorization/rbac)
- [ ] Create new authorization middleware (https://github.com/kubernetes/apiserver/blob/e9e4beec4b157a40f6c742782d74faf45c2b280e/pkg/endpoints/filters/authorization.go)
- [ ] Replace environments & organizations by namespaces
	- [ ] update all existing structs
    - [ ] update store (???)
	- [ ] update sensuctl
	- [ ] all the rest
- [ ] Create/rename store methods to GetX or ListX. (**WARNING** This is only required if the new structs/storage is not implemented soon)
