### ISSUE TITLE
sensuctl env

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#3253]
The ability to output the current sensuctl configuration and state as environment variables. 

The spec document (public) can be found at: https://docs.google.com/document/d/1R3O7vc591NzXSwjQ6Yed6AY7TBahARqB_PFnMAqSCjI/edit?usp=sharing

**Comment by portertech** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [sensuctl env](https://trello.com/c/uw9NYkHk/41-sensuctl-env)

**Comment by palourde** [comment]
## TODO
- [ ] Output environment for bash
- [ ] Output environment for cmd
- [ ] Output environment for powershell
- [ ] Support `--shell` flag
- [ ] Renew the access token before running
- [ ] Add `SENSU_TRUSTED_CA_FILE` & `SENSU_INSECURE_SKIP_TLS_VERIFY`
- [ ] Unit tests
- [ ] E2E (sensu-go-qa-crucible) tests
