### ISSUE TITLE
Asset paths should be available in the context of commands

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#3662]
##  Feature Suggestion

Resources which invoke commands (e.g. checks, pipe handlers, mutators, hooks) should have access to the full path(s) for assets attached to the resource.

## Possible Implementation

Expose asset paths as environment variables in the command execution context. For example, given this check:

```
---
type: CheckConfig
api_version: core/v2
metadata:
namespace: default
name: win-cpu-check
spec:
command: powershell.exe -ExecutionPolicy ByPass -f %ASSET_PATH%\bin\check-windows-cpu-load.ps1 90
95
subscriptions:
- windows
handlers:
- slack
- email
runtime_assets:
- sensu-plugins-windows
interval: 10
publish: true
```

The resulting command execution would have access to the file path for the named runtime asset as `%ASSET_PATH%`.

For checks with multiple assets, perhaps we could iteratively create incrementing variables like `ASSET_PATH_1`, `ASSET_PATH_2` or similar?

## Context

Sensu reports unexpected check status when executing PowerShell plugins, unless the `-f` or `-File` flag is used. This flag requires the absolute path to the PowerShell script for execution, making it difficult to use this flag with PowerShell scripts distributed as assets.

This is not a new issue in Sensu Go, it was also a consideration in Sensu Core (see https://github.com/sensu/sensu/issues/1919). 

See https://github.com/sensu-plugins/sensu-plugins-windows/issues/101 for examples of how this is affecting Sensu Go users.

**Comment by echlebek** [comment]
I could see this working via token substitution.

```
command: powershell.exe -ExecutionPolicy ByPass -f {{ .assetPath "sensu-plugin-windows" }}\bin\check-windows-cpu-load.ps1 90 95
```

**Comment by calebhailey** [comment]
What would be the benefit of exposing this value as a token vs. as an environment variable? Seems the latter would be the more natural fit?

**Comment by calebhailey** [comment]
Related: https://github.com/sensu/sensu-go/issues/3492

**Comment by echlebek** [comment]
The benefit is that by exposing `assetPath` as a function, we can easily address named assets without having to export multiple environment variables. Additionally, the parameter passed to the `assetPath` could be identical to the name of the asset, rather than needing to know an implicit mapping to an environment variable based on the name.

**Comment by palourde** [comment]
We need to schedule a discussion to expand on Eric's proposal. @nikkixdev will schedule something.

**Comment by calebhailey** [comment]
@amdprophet made a really interesting point here that a check can reference multiple assets, so a solution here would need to offer some control over _which_ asset path the user wishes to reference.

**Comment by nikkixdev** [comment]
Requires https://github.com/sensu/sensu-go/issues/3696

**Comment by palourde** [comment]
Some additional context:

The end goal here is to expose the asset path to resources that consume assets. For resources executed on the agent (checks & hooks), we will expose the agent path directly via a custom function of token substitution. However, since token substitution is not supported yet for backend resources (mutators & handlers), we will have to rely on an additional feature to expose it via environment variables, https://github.com/sensu/sensu-go/issues/3492, which in turns relies on https://github.com/sensu/sensu-go/issues/3639.

### Acceptance Criteria
- [ ] A new template function for token substitution can return the path of an asset (e.g. `{{ assetPath "sensu/ruby:1.1.1" }}`
- [ ] This new template function can be called directly from assets, checks & hooks.

### Tasks
- [ ] Create a public function that returns the right asset build based on the provided entity, so we can retrieve the right hash.
	- It also need to support "old" assets that do not use asset builds.
- [ ] Determine how this new template function will retrieve the actual asset path
	- Right now we only provide the resource config (the template) with the entity (the data).
	- The asset might not be installed yet, so we can't rely on the asset manager to know about the entity, since token substitution happens before the asset is downloaded for the first time
	- We could possibly inject it via the entity labels or annotations?
	- We could also modify the token pkg functions so they accept an optional list of interfaces that would be appended to the existing data, so we could pass the asset path & name.
