### ISSUE TITLE
Lay groundwork for React-based Sensu 2.0 dashboard

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/sensu-go#388]
Large nebulous task at the moment, I will break this task out into smaller chunks as I go.

### Concrete

- [x] Upgrade to React v16 [[#411](https://github.com/sensu/sensu-go/issues/411)]
- [x] ~~Tweak webpack configuration (possibly use  webpack-config.)~~ Will wait until changes are necessary and should talk to @izaakschroeder about `webpack-config`s status. 
- [x] Tweak `eslint` config [[#411](https://github.com/sensu/sensu-go/issues/411)]
- [x] Tweak/Add `prettier` config [[#411](https://github.com/sensu/sensu-go/issues/411)]
- [ ] ~~Add guidelines documentation structure, modules, etc.~~ Premature.
- [x] Jest, test runners, etc. [[#411](https://github.com/sensu/sensu-go/issues/411)]
- [ ] ~~Guidlines for writing tests~~ Possibly premature.

### To Investigate

- [x] Determine current state of GraphQL in Go [[#403](https://github.com/sensu/sensu-go/issues/403)]
- [x] If good: Investigate 'modern' Relay v. Redux&GraphQL
- [x] ~~If ugly: Investigate current conventional Redux setup~~
- [x] How do we implement testing into the existing pipeline
- [x] Investigate styling solutions, styled-components seem great but should do due diligence and see how it's working out for current users. [[#409](https://github.com/sensu/sensu-go/issues/409)]
- [x] How do we include web tests and coverage w/ Travis CI runs(?) [#422]
- ....?

### Tasks

- [x] Add React-JSS and material-ui to project #420 
- [x] Routing #421 (w/ 4Catalyzer/found)
- [x] Add linter & tests to Travis CI config #422
- [ ] Update build.sh to build the dashboard #423
- [ ] Base GraphQL endpoint https://github.com/sensu/sensu-go/issues/429
- [ ] Add Relay to the dashboard https://github.com/sensu/sensu-go/issues/430
- [ ] Login page [https://github.com/sensu/sensu-go/issues/430]
- [ ] Tests!
