### ISSUE TITLE
[Web] Base GraphQL endpoint

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/sensu-go#429]
Build just enough to get started on dashboard and to serve as a template for future development.

## 📝 TODO

- [x] Port existing types from `relay-prototype`
- [ ] Expose enough to get started on dashboard.
  - [ ] list events
  - [ ] list checks
  - [x] list entities?
  - [ ] mutators to create & delete checks
  - [ ] ???
- [ ] Custom NodeDefinition to account for environment & organization. 
- [ ] Add tests, tests and then more tests.
- [ ] ~~Organize types, resolvers, helpers, scalars, etc. in their own package(s)~~ not easily feasible w/o running into endless cyclical package dependency issues.
- [x] Query via APId
- [ ] Add proxy in Dashboardd
- [ ] ???
