### ISSUE TITLE
[Web] Relay

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/sensu-go#430]
Add Relay to the project and update the existing pages to use it.

## 📝 TODO

- [ ] Add `react-relay` package
- [ ] Add `found-relay` package for routing
- [ ] Setup Relay environment; network layer should be configurable so that the access token can be updated.
- [ ] Update router configuration for Relay
- [ ] Update events list page
- [ ] Update checks list page
- [ ] Add create check modal to test mutations.
- [ ] ???
