### ISSUE TITLE
Epic: Sensu 7.x: Rework storage and add OSS Postgresql support

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#4609]
## Description

For Sensu 7.x, we'd like to build upon what we've learned by building, maintaining, and supporting Sensu over the last five years. One of the most common points of difficulty in operating Sensu is having to build and maintain a performant etcd cluster. For many IT organizations, this requirement makes using Sensu too difficult. None of the major cloud providers offer hosted etcd, and running etcd on-prem can be tricky to get right for a lot of organizations.

When we initially hit scaling problems with etcd, we made the postgres event store available to help users deal with higher volumes of event writes than etcd could handle. While this was effective, the postgres event store also had an awkward configuration API, and effectively doubled the number of external dependencies of Sensu. It was also only available in the commercial edition of Sensu, complicating the development process between OSS and commercial versions of the software.

We want to double-down on our postgres support. We want to offer postgres support in both OSS Sensu and in the commercial product, and eventually we want Sensu to be able to work with only postgres. Additionally, we want postgres configuration to be done at application start up time, not as a special API.

- [x] https://github.com/sensu/sensu-go/issues/4614
- [x] https://github.com/sensu/sensu-go/issues/4615
- [x] https://github.com/sensu/sensu-go/issues/4616
- [x] https://github.com/sensu/sensu-go/issues/4628
- [x] https://github.com/sensu/sensu-go/issues/4899
- [x] https://github.com/sensu/sensu-go/issues/4900
- [x] https://github.com/sensu/sensu-go/issues/4901
- [x] https://github.com/sensu/sensu-go/issues/4902
- [x] https://github.com/sensu/sensu-enterprise-go/issues/2542

**Comment by calebhailey** [comment]
Related: https://github.com/sensu/sensu-go/issues/4446

**Comment by echlebek** [comment]
Related: https://github.com/sensu/sensu-go/issues/4625

**Comment by ccressent** [comment]
While we are reworking storage, and since it's also suggested in other related issues that we could even, ultimately, not have etcd at all, I was wondering if it would be useful for us to think about relaxing the "Postgres" dependency to just an "SQL store" dependency. Maybe not as loose as "SQL store", but something that's Postgres, MySQL, SQLite compatible.

I have SQLite in mind in particular, because I see it as a way to back use cases that do not need or cannot justify deploying and dealing with Posgres. Setups for testing or developing Sensu and small scale deployments without much load. The types of setups for which a single backend with embedded etcd is currently used.

I don't know how many Postgres specific features we are currently leveraging, if any at all. But I think it would be useful to at least consider not tying ourselves to a specific DB if we can. Different use cases can then pick the DB backend that suits them best.

This also has the advantage of mostly using the same storage code paths, the "SQL store" paths, be it during development, testing or production, increasing our confidence that features are working correctly.

**Comment by echlebek** [comment]
I have a lot of love for sqlite, but we don't use ANSI SQL for the postgres event store. We use postgres-specific DDL, postgres-specific column types, postgres-specific query syntax, postgres-specific locking semantics, and postgres-specific notification facilities.

Porting what we have now over to sqlite would amount to a full rewrite. That said, I do love the idea of having an sqlite dev mode. It would just cost us extra to get it.

**Comment by echlebek** [comment]
This has been completed. While we have some lingering issues or unimplemented components with respect to 6.x, we will address them as separate issues.
