### ISSUE TITLE
Refactor controllers/assets.go to use new pattern

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/sensu-go#521]
From #491.

## TODO

- [x] Implement `AssetsController` in `apid/actions` package.
    - [x] Implement Query [example](https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/backend/apid/actions/checks.go#L42-L64)
    - [x] Implement Find [example](https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/backend/apid/actions/checks.go#L66-L87)
    - [x] Implement Create [example](https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/backend/apid/actions/checks.go#L89-L118)
    - [x] Implement Update [example](https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/backend/apid/actions/checks.go#L120-L153)
- [x] Implement `AssetRouter` in `apid/routers` package. [example](https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/backend/apid/routers/checks.go)
    - [x] GET /assets (query)
    - [x] GET /assets/{name} (find)
    - [x] POST /assets (create) (create)
    - [x] PUT/PATCH /assets/{name} (update)
- [x] Remove old assets controller from `apid/controllers`
- [x] Remove reference to old controller in `apid` package.
- [x] Hookup new router in `apid` package [example](https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/backend/apid/apid.go#L137-L141)

## Checklist

- Query action
    - [x] Filter out unauthorized resources
- Find action
    - [x] Filter out unauthorized resource
    - [x] Check query params(?) Should this result in panic?
- Create action
    - [x] Ensure that the context has the correct org/environment [example](https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/backend/apid/actions/checks.go#L91-L92)
    - [x] Check for existing resource with same unique identifier
    - [x] Guard against users without permission to complete action
    - [x] Validate that resource’s fields are valid
    - [x] Persist resource
- Update action
    - [x] Ensure that the context has the correct org/environment [example](https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/backend/apid/actions/checks.go#L91-L92)
    - [x] Check for existing resource with same unique identifier. Return not found err, if not present.
    - [x] Copy fields to existing resource. [example](https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/backend/apid/actions/checks.go#L139-L140)
    - [x] Guard against users without permission to complete action
    - [x] Validate that resource’s fields are valid
    - [x] Persist resource

## Gotchas

- The path for the asset request handlers might be non-trivial. https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/backend/apid/controllers/assets.go#L25.
- ???
