### ISSUE TITLE
Refactor controllers/entities.go to use new pattern

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/sensu-go#522]
From #491.

## TODO

- [x] Implement `EntitiesController` in `apid/actions` package.
    - [x] Implement Query [example](https://github.com/sensu/sensu-go/blob/cd842665c8b2e5ace0f55398d89df5fe77e7e5e4/backend/apid/actions/checks.go#L42-L60)
    - [x] Implement Find [example](https://github.com/sensu/sensu-go/blob/cd842665c8b2e5ace0f55398d89df5fe77e7e5e4/backend/apid/actions/checks.go#L62-L78)
    - [x] Implement Destroy [example](https://github.com/sensu/sensu-go/blob/cd842665c8b2e5ace0f55398d89df5fe77e7e5e4/backend/apid/actions/checks.go#L146-L169)
- [x] Implement `EntityRouter` in `apid/routers` package. [example](https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/backend/apid/routers/checks.go)
    - [x] GET /entities (query)
    - [x] GET /entities/{name} (find)
    - [x] DELETE /entities/{name} (destroy)
- [x] Remove old entities controller from `apid/controllers`
- [x] Remove reference to old controller in `apid` package.
- [x] Hookup new router in `apid` package [example](https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/backend/apid/apid.go#L137-L141)

## Checklist

- Query action
    - [ ] Filter out unauthorized resources
- Find action
    - [ ] Filter out unauthorized resource
    - [ ] Check query params(?) Should this result in panic?
- Destroy action
    - [ ] Guard against users without permission to complete action
    - [ ] Check for existing resource with same unique identifier. Return not found err, if not present.
    - [ ] Remove resource

## Gotchas

- I know I’m jinxing it by saying this, but, I think this one should be pretty straightforward.
- ???
