### ISSUE TITLE
Refactor controllers/environments.go to use new pattern

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/sensu-go#523]
From #491.

## TODO

- [x] Implement `EnvironmentsController` in `apid/actions` package.
    - [x] Implement Query [example](https://github.com/sensu/sensu-go/blob/cd842665c8b2e5ace0f55398d89df5fe77e7e5e4/backend/apid/actions/checks.go#L42-L60)
    - [x] Implement Find [example](https://github.com/sensu/sensu-go/blob/cd842665c8b2e5ace0f55398d89df5fe77e7e5e4/backend/apid/actions/checks.go#L62-L78)
    - [x] Implement Create [example](https://github.com/sensu/sensu-go/blob/cd842665c8b2e5ace0f55398d89df5fe77e7e5e4/backend/apid/actions/checks.go#L80-L109)
    - [x] Implement Update [example](https://github.com/sensu/sensu-go/blob/cd842665c8b2e5ace0f55398d89df5fe77e7e5e4/backend/apid/actions/checks.go#L111-L144)
    - [x] Implement Destroy [example](https://github.com/sensu/sensu-go/blob/cd842665c8b2e5ace0f55398d89df5fe77e7e5e4/backend/apid/actions/checks.go#L146-L169)
- [x] Implement `EnvironmentRouter` in `apid/routers` package. [example](https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/backend/apid/routers/checks.go)
    - [x] GET /rbac/organizations/:organization/environments (query)
    - [x] GET /rbac/organizations/{organization}/environments/{environment} (find)
    - [x] POST /rbac/organizations/{organization}/environments (create) (create)
    - [x] PUT/PATCH /rbac/organizations/{organization}/environments/{environment} (update)
    - [x] DELETE /rbac/organizations/{organization}/environments/{environment} (destroy)
- [ ] Remove old environment controller from `apid/controllers`
- [x] Remove reference to old controller in `apid` package.
- [x] Hookup new router in `apid` package [example](https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/backend/apid/apid.go#L137-L141)
- [x] Implement update method in cli/client package [example](https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/cli/client/check.go#L29-L46)
- [x] Implement client mock in cli/client/testing [example](https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/cli/client/testing/mock_check_client.go#L11-L15)
- [x] Change the update command (cli/commands/environment package) to use new method [example](https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/cli/commands/check/update.go#L50-L52)
    - [ ] if applicable, ensure that test is updated.

## Checklist

- Query action
    - [ ] Filter out unauthorized resources
- Find action
    - [ ] Filter out unauthorized resource
    - [ ] Check query params(?) Should this result in panic?
- Create action
    - [ ] Ensure that the context has the correct org/environment [example](https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/backend/apid/actions/checks.go#L91-L92)
    - [ ] Check for existing resource with same unique identifier
    - [ ] Guard against users without permission to complete action
    - [ ] Validate that resource’s fields are valid
    - [ ] Persist resource
- Update action
    - [ ] Ensure that the context has the correct org/environment [example](https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/backend/apid/actions/checks.go#L91-L92)
    - [ ] Check for existing resource with same unique identifier. Return not found err, if not present.
    - [ ] Copy fields to existing resource. [example](https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/backend/apid/actions/checks.go#L139-L140)
    - [ ] Guard against users without permission to complete action
    - [ ] Validate that resource’s fields are valid
    - [ ] Persist resource
- Destroy action
    - [ ] Guard against users without permission to complete action
    - [ ] Check for existing resource with same unique identifier. Return not found err, if not present.
    - [ ] Remove resource

## Gotchas

- Probably?
- ???
