### ISSUE TITLE
Refactor controllers/filters.go to use new pattern

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/sensu-go#524]
From #491.

## TODO

- [x] Implement `FiltersController` in `apid/actions` package.
    - [x] Implement Query [example](https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/backend/apid/actions/checks.go#L42-L64)
    - [x] Implement Find [example](https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/backend/apid/actions/checks.go#L66-L87)
    - [x] Implement Create [example](https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/backend/apid/actions/checks.go#L89-L118)
    - [x] Implement Update [example](https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/backend/apid/actions/checks.go#L120-L153)
    - [x] Implement Destroy [example](https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/backend/apid/actions/checks.go#L155-L178)
- [x] Implement `FilterRouter` in `apid/routers` package. [example](https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/backend/apid/routers/checks.go)
    - [x] GET /filters (query)
    - [x] GET /filters/{name} (find)
    - [x] POST /filters (create) (create)
    - [x] PUT/PATCH /filters/{name} (update)
    - [x] DELETE /filters/{name} (destroy)
- [ ] Remove old filter controller from `apid/controllers`
- [ ] Remove reference to old controller in `apid` package.
- [ ] Hookup new router in `apid` package [example](https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/backend/apid/apid.go#L137-L141)
- [ ] Implement update method in cli/client package [example](https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/cli/client/check.go#L29-L46)
- [ ] Implement client mock in cli/client/testing [example](https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/cli/client/testing/mock_check_client.go#L11-L15)
- [ ] Change the update command (cli/commands/filters package) to use new method [example](https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/cli/commands/check/update.go#L50-L52)

## Checklist

- Query action
    - [ ] Filter out unauthorized resources
- Find action
    - [ ] Filter out unauthorized resource
    - [ ] Check query params(?) Should this result in panic?
- Create action
    - [ ] Ensure that the context has the correct org/environment [example](https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/backend/apid/actions/checks.go#L91-L92)
    - [ ] Check for existing resource with same unique identifier
    - [ ] Guard against users without permission to complete action
    - [ ] Validate that resource’s fields are valid
    - [ ] Persist resource
- Update action
    - [ ] Ensure that the context has the correct org/environment [example](https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/backend/apid/actions/checks.go#L91-L92)
    - [ ] Check for existing resource with same unique identifier. Return not found err, if not present.
    - [ ] Copy fields to existing resource. [example](https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/backend/apid/actions/checks.go#L139-L140)
    - [ ] Guard against users without permission to complete action
    - [ ] Validate that resource’s fields are valid
    - [ ] Persist resource
- Destroy action
    - [ ] Guard against users without permission to complete action
    - [ ] Check for existing resource with same unique identifier. Return not found err, if not present.
    - [ ] Remove resource

## Gotchas

- Maybe [this](https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/backend/apid/controllers/filters.go#L127-L133)? 🤷‍♀️
- ???
