### ISSUE TITLE
Refactor controllers/silenced.go to use new pattern

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/sensu-go#529]
From #491.

## TODO

- [x] Implement `SilencedController` in `apid/actions` package.
    - [x] Implement Query [example](https://github.com/sensu/sensu-go/blob/cd842665c8b2e5ace0f55398d89df5fe77e7e5e4/backend/apid/actions/checks.go#L42-L60)
    - [x] Implement Find [example](https://github.com/sensu/sensu-go/blob/cd842665c8b2e5ace0f55398d89df5fe77e7e5e4/backend/apid/actions/checks.go#L62-L78)
    - [x] Implement Create [example](https://github.com/sensu/sensu-go/blob/cd842665c8b2e5ace0f55398d89df5fe77e7e5e4/backend/apid/actions/checks.go#L80-L109)
    - [x] Implement Destroy [example](https://github.com/sensu/sensu-go/blob/cd842665c8b2e5ace0f55398d89df5fe77e7e5e4/backend/apid/actions/checks.go#L146-L169)
- [x] Implement `SilencedRouter` in `apid/routers` package. [[example](https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/backend/apid/routers/checks.go)]
    - [x] `GET /silenced` (query)
    - [x] `POST /silenced` (create)
    - [x] `GET /silenced/{id}` (find)
    - [x] `DELETE /silenced/{name}` (destroy)
    - [x] `GET /silenced/subscriptions/{subscription}` (query)
    - [x] `DELETE /silenced/subscriptions/{subscription}` (destroy)
    - [x] `GET /silenced/checks/{check}` (query)
    - [x] `DELETE /silenced/checks/{check}` (destroy)
- [x] Remove old silenced controller from `apid/controllers`
- [x] Remove reference to old controller in `apid` package.
- [x] Hookup new router in `apid` package [[example](https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/backend/apid/apid.go#L137-L141)]

## Checklist

- Query action
    - [ ] Filter resources based on arguments
    - [ ] Filter out unauthorized resources
- Find action
    - [ ] Filter out unauthorized resource
    - [ ] Check query params(?) Should this result in panic?
- Create action
    - [ ] Ensure that the context has the correct org/environment [[example](https://github.com/sensu/sensu-go/blob/da7b2e5624b0c2403ba1286e2ef41903696355a8/backend/apid/actions/checks.go#L91-L92)]
    - [ ] Check for existing resource with same unique identifier
    - [ ] Guard against users without permission to complete action
    - [ ] Validate that resource’s fields are valid
    - [ ] Persist resource
- Destroy action
    - [ ] Guard against users without permission to complete action
    - [ ] Check for existing resource with same unique identifier. Return not found err, if not present.
    - [ ] Remove resource

## Gotchas

- Filters are mildly different than 🤷‍♀️
- ???
