### ISSUE TITLE
Logging Redaction

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#588]
**As** an operator,
**I want** to obfuscate certain attributes of entities in the logs
**so that** sensitive information is not displayed in the log entries.

###  Background

Sensu 1.x provides basic log event attribute redaction for sensitive data, e.g. credentials. 

By default, Sensu services redact log event attributes with specific keys:

``` ruby
[
  "password", "passwd", "pass",
  "api_key", "api_token", "access_key",
  "secret_key", "private_key",
  "secret"
]
```

Sensu 1.x clients can customize (replace) this list via their definitions, `"redact": []`.

![screen shot 2017-11-21 at 10 42 24 am](https://user-images.githubusercontent.com/149630/33090392-b0b24a42-cea8-11e7-9378-52ba5419b563.png)

1.x docs https://sensuapp.org/docs/1.1/reference/clients.html#client-definition-specification

1.x code https://github.com/sensu/sensu/blob/b32a0c1a88cf8f6f1b377ababcc8d5804a8698a6/lib/sensu/utilities.rb#L92-L120

This issue likely means we need our own logger "shim". We probably want to expose this configuration via ENV and CLI argument, e.g. `LOG_REDACTION` and/or `--log-redaction`.

### Acceptance Criteria

- [x] A default attribute (e.g. `api_key`) is redacted on the agent log entries
- [x] A custom attribute configured (e.g. `mysql_password`) is redacted on the agent log entries
- [x] Sensitive attributes are redacted in keepalive messages sent to the backend
- [x] Sensitive attributes are redacted when fetching an entity through the API

### Tasks

- [x] https://github.com/sensu/sensu-go/issues/874
- [x] https://github.com/sensu/sensu-go/issues/875
- [x] https://github.com/sensu/sensu-go/issues/876

### Definition of Done

- [x] Documentation
- [x] Unit Tests
- [x] Integration or E2E Test
