### ISSUE TITLE
Update MultitenantResource interface

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/sensu-go#606]
After the switch to protobuf we now automatically have getter and setter methods defined for us. As such we can safely update the interface to expect the methods `GetOrganization` and `GetEnvironment`.

As noted by @echlebek in https://github.com/sensu/sensu-go/pull/602#discussion_r152860007.

## Tasks

- [ ] Update interface to match generated getters
- [ ] Remove existing definitions `GetOrg` and `GetEnv`.
- [ ] Remove existing usage of `GetOrg` and `GetEnv`.
